name: docs
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".readthedocs.yaml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".readthedocs.yaml"

jobs:
  build:
    name: build on linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install sphinx
        run: python -m pip install sphinx_rtd_theme sphinx-tabs enum-tools==0.9.0.post1 sphinx-toolbox==2.18.1

      - name: Build docs
        run: sphinx-build -b html ${{ github.workspace }}/docs ${{ github.workspace }}/build/docs/sphinx

      - name: deploy docs to github pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: "${{ github.workspace }}/build/docs/sphinx"
          clean: true
